In [ ]:
import pandas as pd

In [ ]:
sal = pd.read_csv('Salaries.csv', on_bad_lines='skip')

/tmp/ipykernel_7568/3276416400.py:1: DtypeWarning: Columns (3,4,5,6,9,12) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv('Salaries.csv', on_bad_lines='skip')

Check the head of the dataframe

In [ ]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167477 entries, 0 to 167476
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                167477 non-null  int64
 1   EmployeeName      167477 non-null  object
 2   JobTitle          167477 non-null  object
 3   BasePay           166872 non-null  object
 4   OvertimePay       167477 non-null  object
 5   OtherPay          167477 non-null  object
 6   Benefits          131319 non-null  object
 7   TotalPay          167477 non-null  float64
 8   TotalPayBenefits  167475 non-null  float64
 9   Year              167477 non-null  object
 10  Notes             0 non-null       float64
 11  Agency            167475 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(1), object(9)
memory usage: 16.6+ MB

average base-pay determination

In [ ]:
sal['BasePay'] = pd.to_numeric(sal['BasePay'], errors='coerce')
sal['BasePay'].mean()

np.float64(67899.01839633723)

highest overtime pay

In [ ]:
sal['OvertimePay'] = pd.to_numeric(sal['OvertimePay'], errors='coerce')
sal['OvertimePay'].max()

245131.88

What is the Job title of JOSEPH DRISCOLL?

In [ ]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

How much does JOSEPH DRISCOLL make including benefits?

In [ ]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

Highest paid person finding:

In [ ]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].max()]['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

Lowest paid person finding:

In [ ]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()]['EmployeeName']

167476    Joe Lopez
Name: EmployeeName, dtype: object

Average salary yearwise

In [ ]:
sal['Year'] = pd.to_numeric(sal['Year'], errors='coerce')
sal.dropna(subset=['Year'], inplace=True)
sal['Year'] = sal['Year'].astype(int)
sal.groupby('Year')['BasePay'].mean()

Year
2011    63595.554127
2012    70463.681612
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

How many unique job titles are there?

In [ ]:
sal['JobTitle'].nunique()

2159

Top 5 common jobs:

In [ ]:
sal['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator    8675
Special Nurse       4574
Registered Nurse    4506
Police Officer 3    2922
Firefighter         2584
Name: count, dtype: int64

Job titles with only one occurance in 2013

In [ ]:
sum(sal[sal['Year']==2013]['JobTitle'].value_counts()==1)

202

**How many people have Chief in their job title?**

In [ ]:
def chief_string(title):
    if 'chief' in title.lower().split():
        return True
    else:
        return False

In [ ]:
sum(sal['JobTitle'].apply(lambda x: chief_string(x)))

521